name: rightware_test
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

  #Logo
  flutter_launcher_icons: ^0.13.1

  # Core Dependencies
  cupertino_icons: ^1.0.6
  equatable: ^2.0.5
  dartz: ^0.10.1
  get_it: ^7.6.4
  
  # Network
  dio: ^5.4.0
  
  # State Management
  flutter_bloc: ^8.1.3
  
  # UI & Theming
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  
  # Localization
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

  # Environment
  flutter_dotenv: ^5.1.0

  # Utilities
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0
  jwt_decoder: ^2.0.1
  
  # Validation
  form_field_validator: ^1.1.0
  rxdart: ^0.28.0
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.7
  mockito: ^5.4.4
bloc_test: ^9.1.5

flutter:
  uses-material-design: true
  
  # Localization
  generate: true
  
  # Assets (uncomment when you have assets)
  assets:
     - assets/images/
     - assets/icons/
     - assets/lottie/
     - .env

  #analysis_options.yaml
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/logo.png"
  min_sdk_android: 21
  adaptive_icon_background: "#ffffff"
