import 'package:flutter/material.dart';
import 'package:flutter_localizations/flutter_localizations.dart';

class AppLocalizations {
  final Locale locale;
  AppLocalizations(this.locale);

  static AppLocalizations? of(BuildContext context) =>
      Localizations.of<AppLocalizations>(context, AppLocalizations);

  static const LocalizationsDelegate<AppLocalizations> delegate =
      _AppLocalizationsDelegate();

  static const supportedLocales = [Locale('en', 'US'), Locale('ar')];

  static const localizationsDelegates = [
    delegate,
    GlobalMaterialLocalizations.delegate,
    GlobalWidgetsLocalizations.delegate,
    GlobalCupertinoLocalizations.delegate,
  ];

  late Map<String, String> _strings;

  Future<bool> load() async {
    _strings = locale.languageCode == 'ar' ? _ar : _en;
    return true;
  }

  String translate(String key) => _strings[key] ?? key;

  static const Map<String, String> _en = {
    'app_title': 'FlavorRush',
    'app_subtitle': 'Your favourite food, delivered fast',
    'welcome': 'Welcome',
    'welcome_back': 'Welcome Back! 👋',
    'sign_in_to_continue':'Sign in to continue ordering your favourites.',
    'login': 'Login',
    'logout': 'Logout',
    'email': 'Email',
    'email_hint': 'john@example.com',
    'password': 'Password',
    'password_hint': 'Min. 8 characters',
    'forgot_password': 'Forgot Password?',
    'dont_have_account': "Don't have an account?",
    'sign_up': 'Sign Up',
    'sign_up_button': 'Sign Up',
    'or_continue_with': 'or continue with',
    'create_account': 'Create Account',
    'join_us': 'Join Us! 🎉',
    'join_subtitle': 'Create your account and start ordering\nyour favourite meals.',
    'personal_info': 'Personal Info',
    'first_name': 'First Name',
    'first_name_hint': 'John',
    'last_name': 'Last Name',
    'last_name_hint': 'Doe',
    'phone_number': 'Phone Number',
    'phone_hint': '+1 (555) 000-0000',
    'account_details': 'Account Details',
    'confirm_password': 'Confirm Password',
    'confirm_password_hint': 'Re-enter your password',
    'delivery_address': 'Delivery Address',
    'detailed_address': 'Detailed Address',
    'address_hint': 'Street, Building, Apt. number...',
    'set_home_location': 'Set Home Delivery Location',
    'tap_to_set_location': 'Tap to set your location on map',
    'open_map': 'Open Map',
    'map_coming_soon': 'Map picker coming soon!',
    'already_have_account': 'Already have an account? ',
    'loading': 'Loading...',
    'error_occurred': 'An error occurred',
    'retry': 'Try Again',
    'no_data': 'No data available',
    'search': 'Search',
    'cancel': 'Cancel',
    'save': 'Save',
    'delete': 'Delete',
    'edit': 'Edit',
    'add': 'Add',
    'confirm': 'Confirm',
    'yes': 'Yes',
    'no': 'No',
    'ok': 'OK',
    'close': 'Close',
    'back': 'Back',
    'next': 'Next',
    'previous': 'Previous',
    'submit': 'Submit',
    'continue_text': 'Continue',
    'skip': 'Skip',
    'done': 'Done',
    'select': 'Select',
    'selected': 'Selected',
    'optional': 'Optional',
    'required': 'Required',
    'success': 'Success',
    'warning': 'Warning',
    'error': 'Error',
    'info': 'Information',
    'network_error': 'Network Error',
    'server_error': 'Server Error',
    'validation_error': 'Validation Error',
    'authentication_error': 'Authentication Error',
    'authorization_error': 'Authorization Error',
    'not_found_error': 'Not Found',
    'unknown_error': 'Unknown Error',
    'connection_timeout': 'Connection Timeout',
    'no_internet': 'No Internet Connection',
    'invalid_email': 'Invalid Email Address',
    'invalid_password': 'Invalid Password',
    'invalid_phone': 'Invalid Phone Number',
    'field_required': 'This field is required',
    'password_too_short': 'Password must be at least 8 characters',
    'passwords_dont_match': 'Passwords do not match',
    'invalid_format': 'Invalid format',
    'upload_failed': 'Upload failed',
    'download_failed': 'Download failed',
    'file_too_large': 'File is too large',
    'unsupported_file_type': 'Unsupported file type',
    'permissions_denied': 'Permissions denied',
    'settings': 'Settings',
    'profile': 'Profile',
    'account': 'Account',
    'notifications': 'Notifications',
    'privacy': 'Privacy',
    'security': 'Security',
    'help': 'Help',
    'about': 'About',
    'contact_us': 'Contact Us',
    'terms_of_service': 'Terms of Service',
    'privacy_policy': 'Privacy Policy',
    'logout_confirm': 'Are you sure you want to logout?',
    'delete_confirm': 'Are you sure you want to delete this item?',
    'save_changes': 'Save Changes',
    'discard_changes': 'Discard Changes',
    'changes_saved': 'Changes saved successfully',
    'changes_discarded': 'Changes discarded',
    'loading_text': 'Loading...',
    'saving_text': 'Saving...',
    'deleting_text': 'Deleting...',
    'uploading_text': 'Uploading...',
    'downloading_text': 'Downloading...',
    'processing_text': 'Processing...',
    'please_wait': 'Please wait...',
    'operation_completed': 'Operation completed successfully',
    'operation_failed': 'Operation failed',
    'try_again_later': 'Please try again later',
    'contact_support': 'Contact support if the problem persists',
    'forgot_password_title': 'Forgot Password?',
    'forgot_password_subtitle': "Enter your email and we'll send you a reset code.",
    'send_code': 'Send Code',
    'otp_title': 'Verify Email',
    'otp_subtitle': 'Enter the 6-digit code sent to',
    'verify': 'Verify',
    'resend_code': 'Resend Code',
    'resend_in': 'Resend in',
    'reset_password_title': 'New Password',
    'reset_password_subtitle': 'Create a strong password for your account.',
    'new_password': 'New Password',
    'new_password_hint': 'Min. 8 characters',
    'reset_password_button': 'Reset Password',
    'password_reset_success': 'Password reset successfully!',
    'home_greeting_morning': 'Good morning',
    'home_greeting_afternoon': 'Good afternoon',
    'home_greeting_evening': 'Good evening',
    'deliver_to': 'Delivering to',
    'search_hint': 'Search for food, restaurants...',
    'categories_section': 'Categories',
    'popular_section': 'Popular Near You',
    'trending_section': 'Trending Now',
    'special_offers_section': 'Special Offers',
    'see_all': 'See All',
    'nav_home': 'Home',
    'nav_offers': 'Offers',
    'nav_cart': 'Cart',
    'nav_profile': 'Profile',
    'add_to_cart': 'Add',
    'delivery_time_suffix': ' min',
    'offers_placeholder': 'Exclusive offers coming soon!',
    'cart_placeholder': 'Your cart is empty',
    'profile_placeholder': 'Profile coming soon!',
    'profile_title': 'My Profile',
    'edit_profile': 'Edit Profile',
    'full_name': 'Full Name',
    'email_address': 'Email Address',
    'profile_updated': 'Profile updated successfully!',
    'preferences': 'Preferences',
    'security_section': 'Security',
    'about_section': 'About',
    'dark_mode': 'Dark Mode',
    'language_label': 'Language',
    'font_size': 'Font Size',
    'change_password': 'Change Password',
    'current_password': 'Current Password',
    'app_version': 'App Version',
    'terms_conditions': 'Terms & Conditions',
    'member_since': 'Member since 2024',
  };

  static const Map<String, String> _ar = {
    'app_title': 'FlavorRush',
    'app_subtitle': 'إختيارك الأفصل , وتوصيلٍ أسرع',
    'welcome': 'أهلاً وسهلاً',
    'welcome_back': 'أهلا بك مجدداً! 👋',
    'sign_in_to_continue':'قم بتسجل الدخول لتستمر بطلب اطيب الطلبات .',
    'login': 'تسجيل الدخول',
    'logout': 'تسجيل الخروج',
    'email': 'البريد الإلكتروني',
    'email_hint': 'example@mail.com',
    'password': 'كلمة المرور',
    'password_hint': '٨ أحرف على الأقل',
    'forgot_password': 'نسيت كلمة المرور؟',
    'dont_have_account': 'ليس لديك حساب؟',
    'sign_up': 'إنشاء حساب',
    'sign_up_button': 'إنشاء الحساب',
    'or_continue_with': 'أو قم بتسجيل الدخول عبر',
    'create_account': 'إنشاء حساب',
    'join_us': 'انضم إلينا! 🎉',
    'join_subtitle': 'أنشئ حسابك وابدأ طلب وجباتك المفضلة.',
    'personal_info': 'المعلومات الشخصية',
    'first_name': 'الاسم الأول',
    'first_name_hint': 'محمد',
    'last_name': 'اسم العائلة',
    'last_name_hint': 'أحمد',
    'phone_number': 'رقم الهاتف',
    'phone_hint': '٥X XXX XXXX+',
    'account_details': 'بيانات الحساب',
    'confirm_password': 'تأكيد كلمة المرور',
    'confirm_password_hint': 'أعد كتابة كلمة المرور',
    'delivery_address': 'عنوان التوصيل',
    'detailed_address': 'العنوان التفصيلي',
    'address_hint': 'الشارع، المبنى، رقم الشقة...',
    'set_home_location': 'موقع التوصيل إلى المنزل',
    'tap_to_set_location': 'اضغط لتحديد موقعك على الخريطة',
    'open_map': 'افتح الخريطة',
    'map_coming_soon': 'سيتم فتح الخريطة قريباً',
    'already_have_account': 'لديك حساب بالفعل؟ ',
    'loading': 'جارٍ التحميل...',
    'error_occurred': 'حدث خطأ',
    'retry': 'حاول مجدداً',
    'no_data': 'لا توجد بيانات',
    'search': 'بحث',
    'cancel': 'إلغاء',
    'save': 'حفظ',
    'delete': 'حذف',
    'edit': 'تعديل',
    'add': 'إضافة',
    'confirm': 'تأكيد',
    'yes': 'نعم',
    'no': 'لا',
    'ok': 'حسناً',
    'close': 'إغلاق',
    'back': 'رجوع',
    'next': 'التالي',
    'previous': 'السابق',
    'submit': 'إرسال',
    'continue_text': 'متابعة',
    'skip': 'تخطي',
    'done': 'تم',
    'select': 'اختر',
    'selected': 'مختار',
    'optional': 'اختياري',
    'required': 'مطلوب',
    'success': 'نجاح',
    'warning': 'تحذير',
    'error': 'خطأ',
    'info': 'معلومة',
    'network_error': 'خطأ في الشبكة',
    'server_error': 'خطأ في الخادم',
    'validation_error': 'خطأ في التحقق',
    'authentication_error': 'خطأ في المصادقة',
    'authorization_error': 'خطأ في الصلاحيات',
    'not_found_error': 'غير موجود',
    'unknown_error': 'خطأ غير معروف',
    'connection_timeout': 'انتهت مهلة الاتصال',
    'no_internet': 'لا يوجد اتصال بالإنترنت',
    'invalid_email': 'بريد إلكتروني غير صالح',
    'invalid_password': 'كلمة مرور غير صالحة',
    'invalid_phone': 'رقم هاتف غير صالح',
    'field_required': 'هذا الحقل مطلوب',
    'password_too_short': 'كلمة المرور يجب أن تكون ٨ أحرف على الأقل',
    'passwords_dont_match': 'كلمتا المرور غير متطابقتين',
    'invalid_format': 'تنسيق غير صالح',
    'upload_failed': 'فشل الرفع',
    'download_failed': 'فشل التنزيل',
    'file_too_large': 'الملف كبير جداً',
    'unsupported_file_type': 'نوع الملف غير مدعوم',
    'permissions_denied': 'تم رفض الأذونات',
    'settings': 'الإعدادات',
    'profile': 'الملف الشخصي',
    'account': 'الحساب',
    'notifications': 'الإشعارات',
    'privacy': 'الخصوصية',
    'security': 'الأمان',
    'help': 'المساعدة',
    'about': 'عن التطبيق',
    'contact_us': 'اتصل بنا',
    'terms_of_service': 'شروط الخدمة',
    'privacy_policy': 'سياسة الخصوصية',
    'logout_confirm': 'هل أنت متأكد من تسجيل الخروج؟',
    'delete_confirm': 'هل أنت متأكد من حذف هذا العنصر؟',
    'save_changes': 'حفظ التغييرات',
    'discard_changes': 'تجاهل التغييرات',
    'changes_saved': 'تم حفظ التغييرات بنجاح',
    'changes_discarded': 'تم تجاهل التغييرات',
    'loading_text': 'جارٍ التحميل...',
    'saving_text': 'جارٍ الحفظ...',
    'deleting_text': 'جارٍ الحذف...',
    'uploading_text': 'جارٍ الرفع...',
    'downloading_text': 'جارٍ التنزيل...',
    'processing_text': 'جارٍ المعالجة...',
    'please_wait': 'الرجاء الانتظار...',
    'operation_completed': 'تمت العملية بنجاح',
    'operation_failed': 'فشلت العملية',
    'try_again_later': 'الرجاء المحاولة لاحقاً',
    'contact_support': 'تواصل مع الدعم إذا استمرت المشكلة',
    'forgot_password_title': 'نسيت كلمة المرور؟',
    'forgot_password_subtitle': 'أدخل بريدك الإلكتروني وسنرسل لك رمز إعادة التعيين.',
    'send_code': 'إرسال الرمز',
    'otp_title': 'التحقق من البريد',
    'otp_subtitle': 'أدخل الرمز المكون من 6 أرقام المرسل إلى',
    'verify': 'تحقق',
    'resend_code': 'إعادة الإرسال',
    'resend_in': 'إعادة الإرسال بعد',
    'reset_password_title': 'كلمة مرور جديدة',
    'reset_password_subtitle': 'أنشئ كلمة مرور قوية لحسابك.',
    'new_password': 'كلمة المرور الجديدة',
    'new_password_hint': '٨ أحرف على الأقل',
    'reset_password_button': 'إعادة تعيين كلمة المرور',
    'password_reset_success': 'تم إعادة تعيين كلمة المرور بنجاح!',
    'home_greeting_morning': 'صباح الخير',
    'home_greeting_afternoon': 'مساء الخير',
    'home_greeting_evening': 'مساء النور',
    'deliver_to': 'التوصيل إلى',
    'search_hint': 'ابحث عن طعام، مطاعم...',
    'categories_section': 'الفئات',
    'popular_section': 'الأكثر طلباً',
    'trending_section': 'الأكثر رواجاً',
    'special_offers_section': 'عروض خاصة',
    'see_all': 'عرض الكل',
    'nav_home': 'الرئيسية',
    'nav_offers': 'العروض',
    'nav_cart': 'السلة',
    'nav_profile': 'حسابي',
    'add_to_cart': 'أضف',
    'delivery_time_suffix': ' دقيقة',
    'offers_placeholder': 'عروض حصرية قريباً!',
    'cart_placeholder': 'سلتك فارغة',
    'profile_placeholder': 'الملف الشخصي قريباً!',
    'profile_title': 'ملفي الشخصي',
    'edit_profile': 'تعديل الملف',
    'full_name': 'الاسم الكامل',
    'email_address': 'البريد الإلكتروني',
    'profile_updated': 'تم تحديث الملف الشخصي!',
    'preferences': 'التفضيلات',
    'security_section': 'الأمان',
    'about_section': 'حول التطبيق',
    'dark_mode': 'الوضع الداكن',
    'language_label': 'اللغة',
    'font_size': 'حجم الخط',
    'change_password': 'تغيير كلمة المرور',
    'current_password': 'كلمة المرور الحالية',
    'app_version': 'إصدار التطبيق',
    'terms_conditions': 'الشروط والأحكام',
    'member_since': 'عضو منذ ٢٠٢٤',
  };
}

class _AppLocalizationsDelegate
    extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) =>
      ['en', 'ar'].contains(locale.languageCode);

  @override
  Future<AppLocalizations> load(Locale locale) async {
    final localizations = AppLocalizations(locale);
    await localizations.load();
    return localizations;
  }

  @override
  bool shouldReload(_AppLocalizationsDelegate old) => false;
}

extension AppLocalizationsExtension on BuildContext {
  String tr(String key) =>
      AppLocalizations.of(this)?.translate(key) ?? key;
}
